### PR TITLE
Feature: Performance Improvements

### PR DESCRIPTION
**Pull request by marcobiedermann**
- Cache `document` locally which gets minified to a shorter variable name
- Hoist variables to top will improve performance
- Cache elements length which gets calculated on each iteration

### CODE REVIEW

**Comment by LukyVj** [comment]
You're the best, @marcobiedermann :)

**Comment by Haroenv** [comment]
This looks like a good addition, less calls to `.length` can make some impact on larger queries. I'll test this locally first, then I'll merge it

**Comment by Haroenv** [comment]
Hey @marcobiedermann, I'm getting errors when running your version. Are you sure that caching the `document` works? Doesn't `document` need to be given as an argument then? 

Anyway I notice ~1ms improvement when not running the `length` on every query, so that'll be merged for sure.

**Comment by marcobiedermann** [comment]
@Haroenv Sorry, my bad. I fixed it.

**Comment by Haroenv** [comment]
Yep, thanks for your contributions!

**Pull request merged**
